# Generated by Django 3.1.7 on 2021-03-26 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipeingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeIngredients',
        ),
    ]
